const foods = [
    {
        id: "muz",
        name: "banana",
        image: "/food-icons/banana.png",
        calories: 89,
        protein: 1.1,
        carbs: 22.8,
        fat: 0.3,
      },
      {
        id: "fistik",
        name: "peanut butter",
        image: "/food-icons/peanut-butter.png",
        calories: 94,
        protein: 4,
        carbs: 3.1,
        fat: 8.1,
      },
      {
        id: "siyah cikolata",
        name: "dark chocolate",
        image: "/food-icons/chocolate.png",
        calories: 170,
        protein: 2.2,
        carbs: 13,
        fat: 12.1,
      },
      {
        id: "pilav",
        name: "rice",
        image: "/food-icons/rice.png",
        calories: 205,
        protein: 4.3,
        carbs: 44.5,
        fat: 0.4,
      },
      {
        id: "elma",
        name: "apple",
        image: "/food-icons/apple.png",
        calories: 93,
        protein: 0.5,
        carbs: 24.7,
        fat: 0.3,
      },
      {
        id: "havuc",
        name: "carrot",
        image: "/food-icons/carrot.png",
        calories: 25,
        protein: 1,
        carbs: 6,
        fat: 0.1,
      },
      {
        id: "salatalik",
        name: "cucumber",
        image: "/food-icons/cucumber.png",

        calories: 18,
        protein: 0.78,
        carbs: 4.36,
        fat: 0.13,
      },
      {
        id: "haslanmisyumurta",
        name: "egg boiled",
        image: "/food-icons/egg-boiled.png",
        calories: 77,
        protein: 6.3,
        carbs: 0.6,
        fat: 5.3,
      },
      {
        id: "tavadayumurta",
        name: "egg scrambled",
        image: "/food-icons/egg-scrambled.png",
        calories: 91,
        protein: 6,
        carbs: 1,
        fat: 6.7,
      },
      {
        id: "patates",
        name: "potato boiled",
        image: "/food-icons/potato.png",
        calories: 134,
        protein: 2.7,
        carbs: 31.2,
        fat: 0.2,
      },
      {
        id: "domates",
        name: "tomato",
        image: "/food-icons/tomato.png",
        calories: 20,
        protein: 0.97,
        carbs: 4.28,
        fat: 0.22,
      },
      {
        id: "beyazpeynir",
        name: "white cheese",
        image: "/food-icons/cheese.png",
        calories: 93,
        protein: 6.11,
        carbs: 0.76,
        fat: 7.29,
      },
      {
        id: "kasarpeyniri",
        name: "cheddar cheese",
        image: "/food-icons/cheese.png",
        calories: 71,
        protein: 5.4,
        carbs: 0.51,
        fat: 5.32,
      },
      {
        id: "salam",
        name: "salam",
        image:
          "https://s3.amazonaws.com/img.mynetdiary.com/bean/i219.png",
        calories: 45,
        protein: 1.64,
        carbs: 0.64,
        fat: 3.92,
      },
      {
        id: "marul",
        name: "marul",
        image: "/food-icons/marul.png",
        calories: 16,
        protein: 0.9,
        carbs: 1.7,
        fat: 0.2,
      },
      {
        id: "mercimek",
        name: "mercimek",
        image: "/food-icons/soup.png",
        calories: 139,
        protein: 9.3,
        carbs: 20.2,
        fat: 2.8,
      },
      {
        id: "yapraksarma",
        name: "sarma",
        image: "/food-icons/dolma.png",
        calories: 125,
        protein: 4.38,
        carbs: 23.16,
        fat: 1.71,
      },
      {
        id: "bal",
        name: "honey",
        image: "/food-icons/honey.png",
        calories: 30,
        protein: 0.04,
        carbs: 8.24,
        fat: 0,
      },
      {
        id: "pirasa",
        name: "pırasa yemeği",
        image: "/food-icons/pirasa.png",
        calories: 183,
        protein: 3.58,
        carbs: 20.37,
        fat: 2.73,
      },
      {
        id: "tarhana",
        name: "tarhana",
        image: "/food-icons/soup.png",
        calories: 181,
        protein: 6.9,
        carbs: 14.96,
        fat: 9.87,
      },
      {
        id: "ispanak",
        name: "spinach cooked",
        image: "/food-icons/spinach.png",
        calories: 133,
        protein: 4.46,
        carbs: 10,
        fat: 8.12,
      },
      {
        id: "ekmek",
        name: "Bread",
        image: "/food-icons/bread.png",
        calories: 69,
        protein: 3.5,
        carbs: 11.3,
        fat: 1.1,
      },
      {
        id: "tonbaligi",
        name: "tuna fish",
        image: "/food-icons/fish.png",
        calories: 154,
        protein: 18,
        carbs: 0.7,
        fat: 0.8,
      },
      {
        id: "gozleme",
        name: "Patatesli gozleme",
        image: "/food-icons/potato.png",
        calories: 393,
        protein: 10.96,
        carbs: 77,
        fat: 6.81,
      },
      {
        id: "patateskizartmasi",
        name: "potato fries",
        image: "/food-icons/potato-fries.png",
        calories: 312,
        protein: 3.43,
        carbs: 41.44,
        fat: 14.73,
      },
      {
        id: "patateskizartmasi",
        name: "kaymak",
        image: "/food-icons/kaymak.png",
        calories: 29,
        protein: 0.05,
        carbs: 0.17,
        fat: 3.16,
      },
      {
        id: "kek",
        name: "chocolate cake",
        image: "/food-icons/cake.png",
        calories: 268,
        protein: 3.94,
        carbs: 31.2,
        fat: 13.11,
      },
      {
        id: "caseykek",
        name: "casey chocolate cake",
        image: "/food-icons/cake.png",
        calories: 74,
        protein: 0.72,
        carbs: 9.32,
        fat: 3.83
      },
      {
        id: "halley",
        name: "Ülker Halley",
        image: "/food-icons/cake.png",
        calories: 132,
        protein: 1.2,
        carbs: 20.31,
        fat: 5.1,
      },
      {
        id: "patlamismisir",
        name: "popcorn",
        image: "/food-icons/popcorn.png",
        calories: 140,
        protein: 1.73,
        carbs: 10.6,
        fat: 9.81,
      },
      {
        id: "kiymaliborek",
        name: "kıymalı kol böreği",
        image: "/food-icons/gozleme.png",
        calories: 195,
        protein: 7.77,
        carbs: 28.7,
        fat: 5.43,
      },
      {
        id: "manti",
        name: "Manti",
        image: "/food-icons/manti.png",
        calories: 322,
        protein: 7.83,
        carbs: 56.45,
        fat: 6.64,
      },
      {
        id: "siyahzeytin",
        name: "black olives",
        image: "/food-icons/olives.png",
        calories: 8,
        protein: 0.7,
        carbs: 0.4,
        fat: 0.84,
      },
      {
        id: "pisi",
        name: "fried dough",
        image: "/food-icons/hamur.png",
        calories: 122,
        protein: 3.75,
        carbs: 23,
        fat: 1.41,
      },
      {
        id: "yogurt",
        name: "yogurt",
        image: "/food-icons/yogurt.png",
        calories: 122,
        protein: 6.94,
        carbs: 9.32,
        fat: 6.5,
      },
      {
        id: "findik",
        name: "findik",
        image: "/food-icons/findik.png",
        calories: 7,
        protein: 0.11,
        carbs: 0.1,
        fat: 0.65,
      },
    ]

export default foods;